### ISSUE TITLE
Today's exchange rate is a constantly changing number and can lead to user error

### ISSUE THREAD

**Issue by GriffGreen** [dapplion/cryptoFiatExchangeRate#3]
The title says it all, users are looking to prove a specific exchange rate on a certain day... the goal is for this to be a single source of truth... right now it fails at this for anyone using today's date...

My suggestion... let users use coinmarketcap if they want todays exchange rate ;-)

**Comment by dapplion** [comment]
In the this version only past dates are allowed. If no date is chosen the tool defaults to yesterday. With this PR I close the issue https://github.com/dapplion/cryptoFiatExchangeRate/pull/6

In the future it would be nice to add an option to let users pick a day average or an exact date + time rate which will solve the issue. I'm adding an enhancement issue with that.
https://github.com/dapplion/cryptoFiatExchangeRate/issues/7
